// <auto-generated />
namespace GlucosePatrol.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EntryForeignKeyFixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntryForeignKeyFixed));
        
        string IMigrationMetadata.Id
        {
            get { return "202004301641568_EntryForeignKeyFixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
